ci: PLATE-785: Remove old frontend dist from FollowMerge (#5305)

diff --git a/.github/workflows/follow-merge-upstream-repo-sync.yml b/.github/workflows/follow-merge-upstream-repo-sync.yml
--- a/.github/workflows/follow-merge-upstream-repo-sync.yml
+++ b/.github/workflows/follow-merge-upstream-repo-sync.yml
@@ -6,12 +6,11 @@ on:
       - upstream_repo_update
 
 concurrency:
-  group: ${{ github.event.client_payload.repo_name }}-${{ github.event.client_payload.branch_name }}
+  group: ${{ github.workflow }}-${{ github.event.client_payload.branch_name }}
 
 env:
   NODE: 18
   CACHE_NAME_PREFIX: v1
-  STATIC_DIST: 'label_studio/frontend/dist'
   RELEASE_BRANCH_PREFIX: "ls-release/"
   DOCS_TARGET_DIR: "docs/source/tags/"
 
@@ -34,11 +33,9 @@ jobs:
           
           case "${{ github.event.client_payload.repo_name }}" in
             */dm2)
-              echo "frontend_module_dist=${{ env.STATIC_DIST }}/dm" >> $GITHUB_OUTPUT
               echo "copy_src_path=web/libs/datamanager/src" >> $GITHUB_OUTPUT
               ;;
             */label-studio-frontend)
-              echo "frontend_module_dist=${{ env.STATIC_DIST }}/lsf" >> $GITHUB_OUTPUT
               echo "copy_src_path=web/libs/editor/src" >> $GITHUB_OUTPUT
               echo "copy_src_preserve_path=web/libs/editor/src/examples" >> $GITHUB_OUTPUT
               echo "build_lsf_docs=true" >> $GITHUB_OUTPUT
@@ -126,8 +123,95 @@ jobs:
           fetch-depth: 0
           ref: ${{ steps.get-branch.outputs.name }}
 
+# Merge
+
+      - name: Merge
+        id: merge
+        env:
+          BASE_BRANCH: ${{ steps.get-branch.outputs.base_name }}
+          HEAD_BRANCH: ${{ steps.get-branch.outputs.name }}
+          OUR_FILES: "pyproject.toml poetry.lock web"
+        shell: bash
+        run: |
+          set -xeuo pipefail
+          
+          commit_message="Merge branch '${BASE_BRANCH}' into '${HEAD_BRANCH}'"
+          commit_message_workflow_link='Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
+          
+          is-ours() {
+            local my_variable="$1"
+            for e in ${OUR_FILES}; do
+              if [[ "${my_variable}" =~ ^"${e}" ]]; then
+                  return 0
+              fi
+            done
+            return 1
+          }
+          
+          git-resolve-conflict() {
+            STRATEGY="$1"
+            FILE_PATH="$2"
+            tmp_1=$(mktemp)
+            tmp_2=$(mktemp)
+            tmp_3=$(mktemp)
+            git show :1:"${FILE_PATH}" > "${tmp_1}"
+            git show :2:"${FILE_PATH}" > "${tmp_2}"
+            git show :3:"${FILE_PATH}" > "${tmp_3}"
+            git merge-file "${STRATEGY}" -p "${tmp_2}" "${tmp_1}" "${tmp_3}" > "${FILE_PATH}"
+            rm "${tmp_1}" || true
+            rm "${tmp_2}" || true
+            rm "${tmp_3}" || true
+            return 0
+          }
+          
+          if output=$(git merge "origin/${BASE_BRANCH}" -m "${commit_message}" -m "${commit_message_workflow_link}"); then
+            echo "result=true" >> $GITHUB_OUTPUT
+            echo "reaction=+1" >> $GITHUB_OUTPUT
+            output_last_line=$(tail -n1 <<< "${output}")
+            echo "message=Successfully merged: ${output_last_line}" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+          
+          conflict_files=$(git diff --name-only --diff-filter=U)
+          result='true'
+          while read -r conflict_file; do
+            if is-ours "${conflict_file}"; then
+              if git-resolve-conflict --ours "${conflict_file}"; then
+                echo "::notice file=${conflict_file}::Merge Conflict automatically resolved ${conflict_file}"
+                git add "${conflict_file}"
+              else
+                result='false'
+                echo "::error file=${conflict_file}::Failed to automatically resolve ${conflict_file}"        
+              fi
+            else
+              result='false'
+              echo "::error file=${conflict_file}::Could not resolve ${conflict_file}"
+            fi
+          done <<< ${conflict_files}
+          
+          conflict_files=$(git diff --name-only --diff-filter=U)
+          if [ -z "${conflict_files}" ]; then
+            git commit -m "${commit_message}" -m "${commit_message_workflow_link}"
+            echo "result=true" >> $GITHUB_OUTPUT
+            echo "reaction=+1" >> $GITHUB_OUTPUT
+            output_last_line=$(git show --shortstat HEAD | tail -n1)
+            echo "message=Successfully merged: ${output_last_line}" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          echo "result=false" >> $GITHUB_OUTPUT
+          echo "reaction=-1" >> $GITHUB_OUTPUT
+          {
+              echo "message<<EOF"
+              echo "Unresolvable merge conflict detected, please resolve it using the git command line: ${conflict_files}"
+              echo "EOF" 
+            } >> $GITHUB_OUTPUT
+          exit 1
+
+# Frontend
+
       - name: "Frontend: Checkout module"
-        if: steps.details.outputs.frontend_module_dist
+        if: steps.details.outputs.copy_src_path
         uses: actions/checkout@v4
         with:
           repository: ${{ github.event.client_payload.repo_name }}
@@ -136,7 +220,7 @@ jobs:
           fetch-depth: 1
           ref: ${{ github.event.client_payload.commit_sha }}
 
-      - name: Commit src
+      - name: "Frontend: Commit and Push"
         if: steps.details.outputs.copy_src_path
         shell: bash
         env:
@@ -165,101 +249,13 @@ jobs:
           git commit --allow-empty -m '[submodules] Copy src ${{ github.event.client_payload.repo_name }}' -m 'Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
           git push origin HEAD
 
-      - name: "Frontend: Setup nodejs"
-        uses: actions/setup-node@v4
-        if: steps.details.outputs.frontend_module_dist
-        with:
-          node-version: "${{ env.NODE }}"
+# POETRY
 
-      - name: "Frontend: Upgrade Yarn"
-        if: steps.details.outputs.frontend_module_dist
-        run: npm install -g yarn@1.22
-
-      - name: Get yarn cache directory path
-        if: steps.details.outputs.frontend_module_dist
-        id: yarn-cache-dir-path
-        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
-
-      - name: "Frontend: Configure yarn cache"
-        if: steps.details.outputs.frontend_module_dist
-        uses: actions/cache@v3
-        with:
-          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ env.CACHE_NAME_PREFIX }}-${{ runner.os }}-node-${{ env.NODE }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
-
-      - name: "Frontend: Print Yarn cache size"
-        if: steps.details.outputs.frontend_module_dist
-        run: du -d 0 -h ${{ steps.yarn-cache-dir-path.outputs.dir }}
-
-      - name: "Frontend: Install Yarn dependencies"
-        if: steps.details.outputs.frontend_module_dist
-        run: |
-          rm package-lock.json || true
-          yarn install
-        working-directory: tmp
-
-      - name: "Frontend: Build module"
-        if: steps.details.outputs.frontend_module_dist
-        working-directory: tmp
-        env:
-          CI: false # on true webpack breaks on warnings, and we have them a lot
-          NODE_ENV: 'production'
-          TITLE: ${{ github.event.client_payload.title }}
-        run: |
-          yarn run build:module
-          if [[ "${{ github.event.client_payload.event_action }}" == 'merged' ]]; then 
-            branch="${{ github.event.client_payload.base_branch_name }}"
-          else
-            branch="${{ github.event.client_payload.branch_name }}"
-          fi
-          cat << EOF > "build/static/version.json"
-          {
-            "message": "${TITLE}",
-            "commit": "${{ github.event.client_payload.commit_sha }}",
-            "branch": "${branch}",
-            "date": "$(git log -1 --date=format:"%Y-%m-%dT%TZ" --format="%ad" | cat)"
-          }
-          EOF
-
-      - name: "Frontend: LSF Docs: Cache node modules"
-        if: steps.details.outputs.build_lsf_docs
-        uses: actions/cache@v3
-        with:
-          path: ~/.npm
-          key: npm-${{ env.CACHE_NAME_PREFIX }}-${{ runner.os }}-node-${{ env.NODE }}-jsdoc-to-markdown
-
-      - name: "Frontend: LSF Docs: Install NPM deps"
-        if: steps.details.outputs.build_lsf_docs
-        continue-on-error: true
-        run: npm install -g jsdoc-to-markdown node-fetch
-
-      - name: "Frontend: LSF Docs: Build"
-        id: lsf-docs-build
-        if: steps.details.outputs.build_lsf_docs
-        continue-on-error: true
-        working-directory: tmp/scripts
-        run: node create-docs.js
-
-      - name: "Frontend: Commit"
-        if: steps.details.outputs.frontend_module_dist
-        shell: bash
-        run: |
-          set -xeuo pipefail
-
-          rm -rf "${{ steps.details.outputs.frontend_module_dist }}"
-          mkdir -p "${{ steps.details.outputs.frontend_module_dist }}"
-          cp -r tmp/build/static/* "${{ steps.details.outputs.frontend_module_dist }}"
-
-          git add "${{ steps.details.outputs.frontend_module_dist }}"
-          git status -s
-          git commit --allow-empty -m '[submodules] Build static ${{ github.event.client_payload.repo_name }}' -m 'Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
-          git push origin HEAD
-
-      - name: Set up Poetry
+      - name: "Poetry: Set up"
         if: steps.details.outputs.poetry
         uses: snok/install-poetry@v1
 
-      - name: "Requirements: Commit"
+      - name: "Poetry: Commit and Push"
         if: steps.details.outputs.poetry
         shell: bash
         run: |
@@ -272,7 +268,34 @@ jobs:
           git commit --allow-empty -m '[submodules] Bump ${{ github.event.client_payload.repo_name }} version' -m 'Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
           git push origin HEAD
 
-      - name: "Frontend: LSF Docs: Commit"
+# LSF Docs
+
+      - name: "LSF Docs: Setup nodejs"
+        uses: actions/setup-node@v4
+        if: steps.details.outputs.build_lsf_docs
+        with:
+          node-version: "${{ env.NODE }}"
+
+      - name: "LSF Docs: Cache node modules"
+        if: steps.details.outputs.build_lsf_docs
+        uses: actions/cache@v3
+        with:
+          path: ~/.npm
+          key: npm-${{ env.CACHE_NAME_PREFIX }}-${{ runner.os }}-node-${{ env.NODE }}-jsdoc-to-markdown
+
+      - name: "LSF Docs: Install NPM deps"
+        if: steps.details.outputs.build_lsf_docs
+        continue-on-error: true
+        run: npm install -g jsdoc-to-markdown node-fetch
+
+      - name: "LSF Docs: Build"
+        id: lsf-docs-build
+        if: steps.details.outputs.build_lsf_docs
+        continue-on-error: true
+        working-directory: tmp/scripts
+        run: node create-docs.js
+
+      - name: "LSF Docs: Commit and Push"
         if: steps.details.outputs.build_lsf_docs && steps.lsf-docs-build.conclusion == 'success'
         continue-on-error: true
         run: |
@@ -286,41 +309,6 @@ jobs:
           git commit -m 'docs: LSF Update' -m 'Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
           git push origin HEAD
 
-      - name: Merge base branch
-        shell: bash
-        continue-on-error: true
-        run: |
-          set -xeuo pipefail
-          
-          branch='${{ steps.get-branch.outputs.name }}'
-          base_branch='origin/${{ steps.get-branch.outputs.base_name }}'
-          
-          lsf_path='label_studio/frontend/dist/lsf/'
-          dm_path='label_studio/frontend/dist/dm/'
-          
-          git merge "${base_branch}" --message "Merge branch '${base_branch}' into '${branch}'" || true
-
-          git diff --name-only --diff-filter=U --relative
-          
-          git checkout --ours "${lsf_path}"
-          git add "${lsf_path}" || ture
-          
-          git checkout --ours "${dm_path}"
-          git add "${dm_path}" || ture
-          
-          unmerged_files=$(git diff --name-only --diff-filter=U --relative)
-          
-          if [ -z "${unmerged_files}" ]; then
-            echo "No unmerged files found"
-            echo "Pushing merge commit"
-            git commit -m "Merge branch '${base_branch}' into '${branch}'" -m 'Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}' || true
-            git push origin HEAD
-          else
-            echo "Unmerged files found:"
-            echo "${unmerged_files}"  
-            echo "Skipping push"
-            exit 0
-          fi
 
       - name: Find or Create PR
         id: get-pr
